src/Entity/Cars.php
<?php

namespace App\Entity;

use App\Repository\CarsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CarsRepository::class)]
class Cars
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $kilometrage = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $nbproprio = null;

    #[ORM\Column]
    private ?int $cylindree = null;

    #[ORM\Column]
    private ?int $puissancech = null;

    #[ORM\Column]
    private ?int $puissancekw = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $year = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message:'La description ne peut pas etre vide')]
    #[Assert\Length(min:10,minMessage:'La description doit faire au moin 10 caracteres')]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?Modele $modele = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?Carburant $carbu = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?Transmission $transmi = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?TypeDeBoite $typedeboite = null;

    #[ORM\Column(length: 255)]
    private ?string $cover = null;

    #[ORM\ManyToMany(targetEntity: Equipement::class, mappedBy: 'cars')]
    private Collection $equipements;

    #[ORM\OneToMany(mappedBy: 'car', targetEntity: Images::class, cascade: ['persist'])]
    private Collection $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->equipements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKilometrage(): ?int
    {
        return $this->kilometrage;
    }

    public function setKilometrage(int $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getNbProprio(): ?int
    {
        return $this->nbproprio;
    }

    public function setNbProprio(int $nbproprio): self
    {
        $this->nbproprio = $nbproprio;

        return $this;
    }

    public function getCylindree(): ?int
    {
        return $this->cylindree;
    }

    public function setCylindree(int $cylindree): self
    {
        $this->cylindree = $cylindree;

        return $this;
    }

    public function getPuissanceCh(): ?int
    {
        return $this->puissancech;
    }

    public function setPuissanceCh(int $puissancech): self
    {
        $this->puissancech = $puissancech;

        return $this;
    }

    public function getPuissanceKw(): ?int
    {
        return $this->puissancekw;
    }

    public function setPuissanceKw(int $puissancekw): self
    {
        $this->puissancekw = $puissancekw;

        return $this;
    }

    public function getYear(): ?\DateTimeImmutable
    {
        return $this->year;
    }

    public function setYear(\DateTimeImmutable $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIdModele(): ?Modele
    {
        return $this->modele;
    }

    public function setIdModele(?Modele $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getIdCarbu(): ?Carburant
    {
        return $this->carbu;
    }

    public function setIdCarbu(?Carburant $carbu): self
    {
        $this->carbu = $carbu;

        return $this;
    }

    public function getIdTransmi(): ?Transmission
    {
        return $this->transmi;
    }

    public function setIdTransmi(?Transmission $transmi): self
    {
        $this->transmi = $transmi;

        return $this;
    }


    public function getIdTypeDeBoite(): ?TypeDeBoite
    {
        return $this->typedeboite;
    }

    public function setIdTypeDeBoite(?TypeDeBoite $typedeboite): self
    {
        $this->typedeboite = $typedeboite;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;
        return $this;
    }

    /**
     * @return Collection<int, Equipement>
     */
    public function getEquipements(): Collection
    {
        return $this->equipements;
    }

    public function addEquipement(Equipement $equipement): self
    {
        if (!$this->equipements->contains($equipement)) {
            $this->equipements->add($equipement);
            $equipement->addCar($this);
        }

        return $this;
    }

    public function removeEquipement(Equipement $equipement): self
    {
        if ($this->equipements->removeElement($equipement)) {
            $equipement->removeCar($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setCar($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getCar() === $this) {
                $image->setCar(null);
            }
        }

        return $this;
    }

}

src/Controller/ShowRoomController.php
<?php

namespace App\Controller;

use App\Entity\Cars;
use App\Entity\Equipement;
use App\Entity\Images;
use App\Form\AddcarType;
use App\Repository\CarsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ShowRoomController extends AbstractController
{
    #[Route('/showroom', name: 'showroom')]
    public function index(CarsRepository $repo): Response
    {
        $cars = $repo->findAll();

        return $this->render('showroom/index.html.twig', [
            'car' => $cars,
        ]);
    }

    #[Route('/info/car/{id}', name: 'info')]
    public function info(Cars $car): Response
    {
        $id = $car->getId();
        $km = $car->getKilometrage();
        $price = $car->getPrice();
        $proprio = $car->getNbProprio();
        $cylidree = $car->getCylindree();
        $ch = $car->getPuissanceCh();
        $annee = $car->getYear();
        $desc = $car->getDescription();
        $model = $car->getIdModele();
        $carbu = $car->getIdCarbu();
        $transmi = $car->getIdTransmi();
        $img = $car->getImages();
        $boite = $car->getIdTypeDeBoite();
        $opt = $car->getEquipements();

        return $this->render('showroom/info.html.twig', [
            'id' => $id,
            'model' => $model,
            'desc' => $desc,
            'km' => $km,
            'price' => $price,
            'proprio' => $proprio,
            'cylidree' => $cylidree,
            'ch' => $ch,
            'annee' => $annee,
            'carbu' => $carbu,
            'transmi' => $transmi,
            'img' => $img,
            'boite' => $boite,
            'opt' => $opt,
        ]);
    }

    #[Route('/adm/addcar', name: 'addcar')]
    #[IsGranted("ROLE_ADMIN")]
    public function create(Request $request, EntityManagerInterface $manager): Response
    {
        $car = new Cars();
        
        $form = $this->createForm(AddcarType::class, $car);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            // test pour ajouter les equipement (a revoir)
            // $equipements = $form->getData()->getEquipements();
            // for ($e=0; $e <= count($equipements); $e++) {
            //     $equipement = $equipements[$e];
            //     dd($equipement);
            //     foreach ($equipement['name'] as $opt) {
            //         dd($opt);
            //     }
            // }
            $image = $form->get('Image')->getData();
            $img = new Images();
            $img->setUrl($image);
            $car->addImage($img);
            $manager->persist($car);
            $manager->flush();
            return $this->redirectToRoute('info',['id'=>$car->getId()]);
        }

        return $this->render('addcar/addcar.html.twig', [
            'myform' => $form->createView()
        ]);
    }
}

templates/showroom/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ShowRoom{% endblock %}

{% block body %}
    <div class="test">
        <div class="containerCarte">
            {% for cars in car %}
                <div class="carte mt-5">
                    <div class="titre">
                        <span>{{cars.idModele.marque.name}} {{cars.idModele.name}}</span>
                    </div>
                    <img src="{{cars.cover}}" alt="" srcset=""> 
                    <div class="info">
                        <span>Kilometrage {{cars.kilometrage}} KM</span>
                        <span>{{cars.nbproprio}} Propriétaires préc.</span>
                    </div>
                    <div class="info">
                        <span>Prix {{cars.price}} €</span>
                        <span>Date {{cars.year | date('d/m/y')}}</span>
                    </div>
                    <div class="btn mt-4">
                        <a href="{{path('info',{'id': cars.id})}}">Plus d'info</a>
                    </div>
                </div>
            {% endfor %}
                  
        </div>
    </div>
{% endblock %}

templates/showroom/info.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{model.marque.name}} {{model.name}}{% endblock %}

{% block body %}
    <div class="container full">
        <p>{{model.marque.name}} {{model.name}}</p>
        <div class="carousel">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
                <div class="carousel-indicators">
                    {% for image in img %}
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{loop.index0}}" {% if loop.first %} class="active" aria-current="true" {% endif %} aria-label="Slide {{loop.index}}"></button>
                    {% endfor %}  
                </div>
                <div class="carousel-inner">
                    {% for image in img %}
                        <div class="carousel-item {% if loop.first %}active{% endif %}">
                            <img class='carousel' src="{{image.Url}}" alt="image de {{image.id}}">
                        </div>
                    {% endfor %}
                    
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <p>annee model : {{model.yearModele}}</p>
        <p>desc : {{desc}}</p>
        <p>price : {{price}}</p>
        <p>KM : {{km}} km</p>
        <p>proprio : {{proprio}}</p>
        <p>cylidree : {{cylidree}}</p>
        <p>ch : {{ch}}</p>
        <p>annee : {{annee | date('d/m/y')}}</p>
        <p>carbu : {{carbu.type}}</p>
        <p>transmi : {{transmi.type}}</p>
        <p>boite : {{boite.type}}</p>
            <h6>Equipements</h6>
            <ul>
        {% for equipement in opt %}
                <li>{{equipement.name}}</li>
        {% endfor %}
            </ul>
        <div class="btn mt-4">
            <a href="{{path('showroom')}}">Retour au showroom</a>
        </div>
    </div>
{% endblock %}